### ISSUE TITLE
[feature]Support type for parameter

### ISSUE THREAD

**Issue by wonderflow** [cloud-native-application/RudrX#13]
At least, we need support below four types:

* string
* int
* float
* image: special type, it's real type is string, but can do more, such as [build image from source code(git url)](https://github.com/cloud-native-application/RudrX/issues/14).

```yaml
apiVersion: core.oam.dev/v1alpha2
kind: WorkloadDefinition
...
    parameters: 
      - name: image # --image
        short: i # -i
        required: true
        type: image
        fieldPaths: 
        - "spec.containers[0].image"
      - name: port # --port
        short: p # -p
        required: false
        type: int
        fieldPaths:
        - "spec.containers[0].ports[0].containerPort"
    lastCommandParam: image # so image will become the default command
```
